'use client';
import { useState } from 'react';
import { DemoNotice, PageHeader, StatusBadge } from '@/components/erp-ui';
const steps = ['파일 선택', '형식 확인', '행사 자동 매칭', '일매출 등록'];
export default function RevenuesPage() {
  const [file, setFile] = useState<File | null>(null); const [step, setStep] = useState(0);
  return <div><PageHeader eyebrow="REVENUE" title="매출 관리" description="마트 매출 Excel을 행사 일정과 연결하는 표준 흐름을 준비했습니다." />
    <DemoNotice>Excel 파일은 서버로 전송되지 않습니다. 이번 MVP에서는 업로드 흐름과 검증 화면만 제공합니다.</DemoNotice>
    <div className="mb-6 grid grid-cols-2 border border-gray-200 bg-white md:grid-cols-4">{steps.map((label, index) => <div key={label} className={`border-r border-gray-200 p-4 ${index <= step ? 'bg-emerald-50' : ''}`}><span className="text-xs font-bold text-gray-400">0{index + 1}</span><p className={`mt-1 text-sm font-bold ${index <= step ? 'text-emerald-800' : 'text-gray-500'}`}>{label}</p></div>)}</div>
    <section className="grid gap-6 xl:grid-cols-[1fr_1.2fr]"><div className="border border-gray-200 bg-white p-6"><h2 className="font-bold">Excel 업로드</h2><p className="mt-1 text-sm text-gray-500">서로 다른 마트 양식도 향후 매핑 규칙으로 관리합니다.</p><label className="mt-5 flex min-h-44 cursor-pointer flex-col items-center justify-center border-2 border-dashed border-gray-300 bg-gray-50 p-5 text-center"><span className="text-3xl text-emerald-700">⇧</span><span className="mt-2 text-sm font-bold">.xlsx 또는 .xls 파일 선택</span><span className="mt-1 max-w-xs truncate text-xs text-gray-500">{file?.name || '선택된 파일 없음'}</span><input type="file" accept=".xlsx,.xls" className="hidden" onChange={(e) => { setFile(e.target.files?.[0] || null); setStep(0); }} /></label><button disabled={!file} onClick={() => file && setStep(1)} className="mt-4 w-full bg-emerald-700 px-4 py-2.5 text-sm font-bold text-white disabled:bg-gray-300">파일 형식 확인</button></div>
      <div className="border border-gray-200 bg-white"><div className="flex items-center justify-between border-b border-gray-200 px-5 py-4"><h2 className="font-bold">매칭 미리보기</h2><StatusBadge tone={step ? 'amber' : 'gray'}>{step ? '검토 필요' : '대기'}</StatusBadge></div><div className="overflow-x-auto"><table className="w-full min-w-[560px] text-sm"><thead className="bg-gray-50 text-left text-xs text-gray-500"><tr><th className="px-4 py-3">날짜</th><th className="px-4 py-3">마트</th><th className="px-4 py-3">행사팀</th><th className="px-4 py-3">매출액</th><th className="px-4 py-3">매칭</th></tr></thead><tbody><tr><td colSpan={5} className="px-4 py-16 text-center text-gray-500">{step ? '파일 파싱 엔진 연결 전입니다. Excel 샘플 확인 후 구현합니다.' : '파일을 선택하고 형식을 확인해 주세요.'}</td></tr></tbody></table></div></div>
    </section><div className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{['일매출', '주간 집계', '월간 집계', '마트/팀별 집계'].map((item) => <div key={item} className="border border-gray-200 bg-white p-4"><p className="text-xs text-gray-500">{item}</p><p className="mt-2 text-xl font-bold">-</p><p className="mt-1 text-xs text-amber-700">매출 DB 연결 전</p></div>)}</div>
  </div>;
}
